#!/bin/bash
TOKEN="7485676285:AAGLOZHJAU2-N9rs-KEh8M9e12E0zijdWt0oE" # Utilize o seu TOKEN
 
USER=$1
SUBJECT=$2
MESSAGE=$3
NL="
"
curl --silent -X POST --data-urlencode "chat_id=${USER}" --data-urlencode "text=${SUBJECT}${NL}${NL}${MESSAGE}" "https://api.telegram.org/bot${TOKEN}/sendMessage?disable_web_page_preview=true&parse_mode=html" | grep -q '"ok":true'
 
exit 0
